version: "3.9"
services:
  nmt-streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./model:/app/model
      - ./outputs:/app/outputs
    environment:
      - TRANSFORMERS_CACHE=/app/.cache
    restart: unless-stopped
